### ISSUE TITLE
Unable to register an Artifact if the record Id's length is greater than 63 chars

### ISSUE THREAD

**Issue by vsevel** [Apicurio/apicurio-registry-content-sync-operator#100]
When a CR `Artifact` gets created, labels get automatically added:
```
apicur.io/artifactId: org.acme.kafka.quarkus.Movie
apicur.io/version: '1'
apicur.io/groupId: default
```

There is an issue if one of those values's length is greater than 63 chars, as described [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set).

So if we attempt to create an artifactId with more than 63 chars in it, the operator will fail putting the labels.

the apicurio has several options:
- veto the creation of the `Artifact` CR if one of those fields is greater than 63 chars
- change the status to error
- use annotations instead of label to store this information, if those fields are not used as selectors
- store a label with a hashed value, instead of the full value

for the last option, here is what we are doing in similar situations:

```
    private String truncate(String string, int maxLength) {
        if (string.length() > maxLength) {
            Checksum checksum = new CRC32();
            checksum.update(string.getBytes(), 0, string.length());
            String suffix = "-" + Long.toHexString(checksum.getValue());
            string = string.substring(0, maxLength - suffix.length()) + suffix;
        }
        return string;
    }
```

**Comment by andreaTP** [comment]
Hi @vsevel , I looked into this issue and went for the last option:

> store a label with a hashed value, instead of the full value

You can test out the changes using this container image of the operator: `docker.io/andreatp/apicurio-registry-kube-sync:latest-snapshot`
