### ISSUE TITLE
Create Helm chart for registry and kube-sync

### ISSUE THREAD

**Issue by eshepelyuk** [Apicurio/apicurio-registry-content-sync-operator#11]
Related to https://github.com/Apicurio/apicurio-registry/discussions/1498

@EricWittmann @famartinrh - cold you please assign this to me ?

**Comment by eshepelyuk** [comment]
Progress can be trackin in WIP PR #12

**Comment by eshepelyuk** [comment]
Hi all,

A new repository is created https://github.com/eshepelyuk/apicurio-registry-helm-chart.
It's still WIP, but progress can be tracked in `main` branch.

**Comment by eshepelyuk** [comment]
@EricWittmann @famartinrh 
I assume that current version of Helm chart from  https://github.com/eshepelyuk/apicurio-registry-helm-chart is ready to be used for basic scenarios and could be shared for public usage.

I would like to get in closer touch with you to discuss my current work, the design approaches and reasons and possibility of project adoption by Apicurio team. The most convenient way would be any kind of conference call in Zoom, Google Meet or smth.

**Comment by kmandal-volvo** [comment]
> @EricWittmann @famartinrh
> I assume that current version of Helm chart from https://github.com/eshepelyuk/apicurio-registry-helm-chart is ready to be used for basic scenarios and could be shared for public usage.
> 
> I would like to get in closer touch with you to discuss my current work, the design approaches and reasons and possibility of project adoption by Apicurio team. The most convenient way would be any kind of conference call in Zoom, Google Meet or smth.

Thanks a lot for the quick turn back. As suggested deployed using an image but with this get a lot of flexibility as environment boundary will not come into the picture as it parameter base.

**Comment by EricWittmann** [comment]
> @EricWittmann @famartinrh
> I assume that current version of Helm chart from https://github.com/eshepelyuk/apicurio-registry-helm-chart is ready to be used for basic scenarios and could be shared for public usage.
> 
> I would like to get in closer touch with you to discuss my current work, the design approaches, solution chosen and possibility of project adoption by Apicurio team. The most convenient way would be any kind of conference call in Zoom, Google Meet or smth.

Sure we can probably make something like that happen.  Feel free to email me directly (email address is on my GitHub account).

**Comment by kmandal-volvo** [comment]
> > @EricWittmann @famartinrh
> > I assume that current version of Helm chart from https://github.com/eshepelyuk/apicurio-registry-helm-chart is ready to be used for basic scenarios and could be shared for public usage.
> > I would like to get in closer touch with you to discuss my current work, the design approaches, solution chosen and possibility of project adoption by Apicurio team. The most convenient way would be any kind of conference call in Zoom, Google Meet or smth.
> 
> Sure we can probably make something like that happen. Feel free to email me directly (email address is on my GitHub account).

Hi Eric,

Released helm chart delayed as expected but while configuring underlying storage of registry data:

In-memory /PostgreSQL 12 database / Apache Kafka 2.6 using below resource instance getting deployment issue  **The server could not find the requested resource**

https://github.com/Apicurio/apicurio-registry-operator/tree/master/config/examples/resources
```
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry-mem
spec:
  configuration:
    persistence: "mem"
```
Thanks
Kallol Mondal

**Comment by eshepelyuk** [comment]
@kmandal-volvo chart is release and avaialbe for usage.
Check README 
https://github.com/eshepelyuk/apicurio-registry-helm-chart

**Comment by kmandal-volvo** [comment]
> @kmandal-volvo chart is released and available for usage.
> 
> Check:
> 
> * README  https://github.com/eshepelyuk/apicurio-registry-helm-chart
> * List of released versions https://github.com/eshepelyuk/apicurio-registry-helm-chart/releases

Yes correct, deployed the same but in chart, there is no option to define underlying storage of registry data for that I have to create an instance that time it complaining may be I have not using right API version for that instance

**Comment by eshepelyuk** [comment]
Yes, you're right, only in mem is supported for now

**Comment by kmandal-volvo** [comment]
> Yes, you're right, only in mem is supported for now.
> But, what you can do for now is:
> 
> 1. generate manifests
> 
> ```
> helm template my-chart ...  > apicurio.yaml
> ```
> 
> 1. patch resulting manifests with required parameters
> 2. install them with `kubectl`
> 
> ```
> kubectl apply -f apicurio.yaml
> ```

Yes, it will generate the deployment descriptor but the same is deployed using the helm chart provided. when I deployed using the helm template it has two deployments one apicurio-registry-sync and apicurio-registry due to that it has two pod for different deployment.

**Comment by eshepelyuk** [comment]
Use only one approach !
Delete installed helm chart,generate and install only patched manifests.

**Comment by eshepelyuk** [comment]
@kmandal-volvo please try the latest version https://github.com/eshepelyuk/apicurio-registry-helm-chart/releases/tag/1.1.0

It introduces support for configuring persistence for a registry instance.

**Comment by kmandal-volvo** [comment]
For persistence: "mem" I believe doesn't have to mention anything in the value file.I want to maintain schema registry persistence in Kafka or Postgres need to uncomment that part and provide configuration.
## uncomment and adjust for Kafka persistence
  # kafka:
  #   bootstrapServers: kafka1:9092,kafka2:9092

  ## uncomment and adjust for sql persistence
  # sql:
  #   url: jdbc:postgresql://postgres/apicurio-registry
  #   username: apicurio
  #   password: apicurio-password

**Comment by eshepelyuk** [comment]
> For persistence: "mem" I believe doesn't have to mention anything in the value file.I want to maintain schema registry persistence in Kafka or Postgres need to uncomment that part and provide configuration.
> 
> ## uncomment and adjust for Kafka persistence
> # kafka:
> # bootstrapServers: kafka1:9092,kafka2:9092
> ## uncomment and adjust for sql persistence
> # sql:
> # url: jdbc:postgresql://postgres/apicurio-registry
> # username: apicurio
> # password: apicurio-password

What is this post about, is this a question ? I didn't understand your intentions :(
Could you try the latest version with persistence config support or not ?

**Comment by kmandal-volvo** [comment]
Not yet tested with persistence it will take some time to configure the same. Is persistence: "mem" by default ? if we don't other persistency or we need to mention. This is the question for which posted last time.

**Comment by eshepelyuk** [comment]
> Not yet tested with persistence it will take some time to configure the same. Is persistence: "mem" by default ? if we don't other persistency or we need to mention. This is the question for which posted last time.

1. yes, in memory persistence is the default, no need to change any helm values.
1. to enable kafka or sql - check out `values.yaml`

**Comment by eshepelyuk** [comment]
The chart is created and available https://github.com/eshepelyuk/apicurio-registry-helm

All chart related issues maybe addressed there.
