### ISSUE TITLE
Updating artifacts

### ISSUE THREAD

**Issue by cemo** [Apicurio/apicurio-registry-content-sync-operator#15]
Hi, 

In our scenario, I would like to have an application with different versions with multiple environments and each updates in cluster I would like to deploy the artifact to registry. We are patching our kubernetes deployments for deploying a new version. 

I am considering to use something like [openapi-external-content](https://github.com/Apicurio/apicurio-registry-content-sync-operator/blob/main/dist/kubernetes/examples/openapi-external-content.yaml). How can I understand that there is a successful deployment and I should update the CRD?

**Comment by cemo** [comment]
Hey @famartinrh and @EricWittmann, 

First of all we are grateful to share such a project with us. This will definitely gain attention in future and we will invest here too with our team.

There are some major companies are also [using same approach ](https://engineering.zalando.com/posts/2019/04/developing-zalando-apis.html)I shared in my previous question. 

One another problem is that detecting new `versions` of deployments. What do you suggest for it?

**Comment by famartinrh** [comment]
I'm not sure I understand you :)

In the example I gave you the user is who actually explicitly specify the version of the Artifact.

What do you refer to by "deployment"? :)

**Comment by cemo** [comment]
@famartinrh would you please give us a brief that we may contribute to project with our team.

**Comment by famartinrh** [comment]
sorry @cemo what info do you exactly need?

**Comment by famartinrh** [comment]
Hi @cemo , we are doing some updates to add missing features to this project, you may want to check it out again. :)

**Comment by cemo** [comment]
@famartinrh I am sorry I missed this issue. I will take a look new implementation.

**Comment by cemo** [comment]
I have not seen any improvement about updating artifacts.
