### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by famarting** [Apicurio/apicurio-registry-content-sync-operator#17]
Either unit tests or integration tests, but we need tests to verify the `ArtifactController` class

**Comment by eshepelyuk** [comment]
@famartinrh 
In my helm chart i've implemented basic e2e test using k3d cluster.
Please use it if you find it helpful.

https://github.com/eshepelyuk/apicurio-registry-helm

**Comment by carlesarnal** [comment]
Tests were added some time ago.
