### ISSUE TITLE
[question] is project dead ?

### ISSUE THREAD

**Issue by eshepelyuk** [Apicurio/apicurio-registry-content-sync-operator#18]
Hi all

What is the status of this project ? Is it abandoned is it planned to be improved ?

**Comment by famartinrh** [comment]
Hi

no, it's not dead, I'm sorry it may look like that :(

this past months we have been quite busy working in other projects of the Apicurio organization. We have plans to continue improving this project.

First thing will be cleaning, testing and upgrading dependencies, so it's safer for us to add new features ...

Thank you for your interest in the project
