### ISSUE TITLE
Release management and version tag

### ISSUE THREAD

**Issue by eshepelyuk** [Apicurio/apicurio-registry-content-sync-operator#32]
Hello

The project needs some basic release management and git tagging.

I.e. currently the docker image is pushed without any meaningful tags. Instead on a new release - corresponding git tagsshould be created and docker image should be oushed with a new tag.

This is critical to be able to pin a particular version when deploying this operator to k8s.

**Comment by famartinrh** [comment]
completely agree, we need this.

I think the easiest thing could be to use the commit hash to tag the image, that way we don't have the need to create a release yet.

wdyt? would that be useful?

**Comment by eshepelyuk** [comment]
Yes, definately it will help right now, to better manage pinned version of the project.

**Comment by famartinrh** [comment]
done, https://quay.io/repository/apicurio/apicurio-registry-kube-sync?tab=tags

**Comment by eshepelyuk** [comment]
Amazing, thnx !
