### ISSUE TITLE
Version deletion bug

### ISSUE THREAD

**Issue by eshepelyuk** [Apicurio/apicurio-registry-content-sync-operator#36]
Hello 

Not sure it is related to this operator or to registry itself.

I am using apicurio with kafka persistance.
Also I am using confluent compatibility API for my producer / consumers.

I've registered 2 versions of Avro schema via `Artifact` CRD and they displayed OK.

1. Then, I've used CC API to retrieve list of versions for my subject, list return 2 item
2. I'm using CC API to delete latest version (#2), deletion is OK
3. Getting list of versions now return 1 item (expected)

But when I log in into UI - i don't see my artifact / subject at all. I've tried to restart both operator and UI - no effect.

So this is a bug I see now

* CC API returns subject and version
* UI doesn't display them at all

**Comment by famartinrh** [comment]
Hi, I've been looking at this today. Looks like a bug in apicurio-registry storage layer. We should track this bug in apicurio-registry repo. can you open this issue there?

**Comment by eshepelyuk** [comment]
@famartinrh opened a new one https://github.com/Apicurio/apicurio-registry/issues/2185
thnx
